export const GET_ERRORS = "GET_ERRORS";
export const CURRENT_ACTION = "CURRENT_ACTION";
export const GET_MOUNTS_DATA = "GET_MOUNTS_DATA";
export const CURRENT_MOUNT = "CURRENT_MOUNT";
export const GET_CURRENT_MOUNT_DATA = "GET_CURRENT_MOUNT_DATA";
